name = 'SilenceSusuka\'sblog'
license = 'MIT'
licenselink = 'https://github.com/SilenceSusuka/MyBlog/blob/main/LICENSE'
description = 'A Hakurei Reimu style Hugo theme'
homepage = 'https://silencesusuka.github.io/MyBlog'
demosite = 'https://d-sketon.github.io/hugo-theme-reimu'

tags = ['Blog', 'Chinese', 'Responsive', 'Dark', 'Light']
features = ['Blog', 'Chinese', 'Responsive', 'Dark', 'Light']

[author]
name = 'SilenceSusuka'
homepage = 'https://silencesusuka.github.io/'
